/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAuditReport, IAuditReportInterface } from "../IAuditReport";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "leaderboard",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "thresoldPoint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAuditReport__factory {
  static readonly abi = _abi;
  static createInterface(): IAuditReportInterface {
    return new utils.Interface(_abi) as IAuditReportInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAuditReport {
    return new Contract(address, _abi, signerOrProvider) as IAuditReport;
  }
}
